/**
 * THE RAIL LAYOUT KIT under test: the fan generated by the template (no hand table), a second composition on disk
 * (the controls bench fixture), determinism, and the deliberate defects each refused for its NAMED reason.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { railLayout, railInputFrom, validateRailLayout, structuralHash, BODY_GEOMETRY, terminalAt, RailLayoutError, TEMPLATE_VERSION, checkGeometry3D, cablePoints3, layoutWires3, layoutBodies, layoutTerminals, layoutNets, ROWS, type RailLayout, type DeckKind, type Wire3 } from './rail-layout';
import { FAN_COMPOSITION } from '../model/fan';
import type { Composition, PartInstance } from '../model/conformance/composition';

const FAN_GROUPS = ['sensing', 'control', 'power'];
const fanGroup = (p: PartInstance): string => ({ s: 'sensing', rb: 'sensing', p: 'sensing', c: 'control', q: 'control', m: 'power', fw: 'power' } as Record<string, string>)[p.name] ?? 'control';
const gen = (c: Composition, groupOf = fanGroup, groups = FAN_GROUPS) => railLayout(railInputFrom(c, groupOf, groups), structuralHash(c));
const clone = <T>(v: T): T => JSON.parse(JSON.stringify(v));
const controls = JSON.parse(readFileSync(new URL('../../tools/conformance/fixtures/controls-bench.composition.json', import.meta.url), 'utf8')) as Composition;
const controlsGroup = (p: PartInstance): string => ({ t: 'supply', p: 'reference', rs: 'load', l: 'load' } as Record<string, string>)[p.name] ?? 'load';

describe('the rail template on the fan', () => {
  it('lays out the fan from its composition alone: roles from port patterns, three zones, rails, drops, no hand coordinates', () => {
    const L = gen(FAN_COMPOSITION);
    expect(Object.keys(L.poses).sort()).toEqual(['c', 'fw', 'm', 'p', 'q', 'rb', 's']);
    expect(L.poses.p.role).toBe('rail-ground'); expect(L.poses.s.role).toBe('rail-signal'); expect(L.poses.rb.role).toBe('signal-ground');
    expect(L.poses.c.role).toBe('signal-signal'); expect(L.poses.q.role).toBe('signal-ground'); expect(L.poses.m.role).toBe('motor'); expect(L.poses.fw.role).toBe('signal-rail');
    // zones read left to right, the divider resistor stacked under the thermistor in one column
    expect(L.poses.p.x).toBeLessThan(L.poses.s.x); expect(L.poses.s.x).toBeLessThan(L.poses.c.x); expect(L.poses.c.x).toBeLessThan(L.poses.q.x); expect(L.poses.q.x).toBeLessThan(L.poses.m.x);
    expect(L.poses.rb.x).toBe(L.poses.s.x); expect(L.poses.rb.z).toBeGreaterThan(L.poses.s.z);
    // every rail/ground terminal has a drop and is a bus member; the two buses span their members
    expect(L.busMembers.rail.map((m) => m.part).sort()).toEqual(['c', 'fw', 'm', 'p', 's']); expect(L.busMembers.ground.map((m) => m.part).sort()).toEqual(['c', 'p', 'q', 'rb']);
    expect(L.rail.x1).toBeGreaterThanOrEqual(Math.max(...L.busMembers.rail.map((m) => m.x))); expect(L.ground.x1).toBeGreaterThanOrEqual(Math.max(...L.busMembers.ground.map((m) => m.x)));
    // the rotor sits ahead of the can, clear of everything, and above the deck
    expect(L.rotor).not.toBeNull(); expect(L.rotor!.z).toBeGreaterThan(L.poses.m.z);
    expect(L.rotor!.hubY - L.rotor!.radius).toBeGreaterThanOrEqual(0.15 - 1e-9); expect(L.poses.m.mount).toBeCloseTo(1.3 + 0.15 - 0.68, 6);   // the motor is RAISED, the blades are not shrunk
    const report = validateRailLayout(L, FAN_COMPOSITION);
    expect(report.diagnostics.filter((x) => x.severity === 'error')).toEqual([]);
    expect(report.ok).toBe(true);
    expect(report.diagnostics.filter((x) => x.cause === 'lifted-crossing').length).toBeGreaterThan(0);   // the reference hop is reported, not hidden
  });
  it('is deterministic: two generations are byte-identical, and electrical edits (volts, temperature points) do not move it', () => {
    const a = JSON.stringify(gen(FAN_COMPOSITION)), b = JSON.stringify(gen(FAN_COMPOSITION));
    expect(a).toBe(b);
    const hot = clone(FAN_COMPOSITION); (hot.sources[0] as { volts: number }).volts = 9; hot.environments![0].points[2].value = 40;
    expect(JSON.stringify(gen(hot))).toBe(a);
    expect(structuralHash(hot)).toBe(structuralHash(FAN_COMPOSITION));
  });
  it('terminal geometry: chord ends, the pot wiper, the comparator pins and the MOSFET gate pin come from the table, oriented with the pose', () => {
    const L = gen(FAN_COMPOSITION);
    const c = L.poses.c; expect(terminalAt(c, 'inp').x).toBeCloseTo(c.x - 0.7, 6); expect(terminalAt(c, 'out').x).toBeCloseTo(c.x + 0.5, 6);   // the tip and the out pin, as drawn
    expect(terminalAt(c, 'inn').z).toBeCloseTo(c.z + 0.5, 6); expect(terminalAt(c, 'vcc').y).toBe(0.4);
    const q = L.poses.q; expect(terminalAt(q, 'gate').z).toBeCloseTo(q.z + 0.7, 6); expect(terminalAt(q, 'gate').x).toBeCloseTo(q.x, 6);   // pins leave toward +z whatever way the chord runs
    const m = L.poses.m; expect(terminalAt(m, 'shaft').y).toBeCloseTo(0.68 + m.mount!, 6); expect(terminalAt(m, 'plus').x).toBeCloseTo(m.x + 0.48 * 2.5, 6);   // posts at lerp .26/.74 of the chord
    expect(() => terminalAt(q, 'wiper')).toThrow(RailLayoutError);
  });
});

describe('a second composition: the controls bench fixture (switch, pot, series resistor, LED)', () => {
  it('lays out and validates without a coordinate table', () => {
    const L = railLayout(railInputFrom(controls, controlsGroup, ['supply', 'reference', 'load']), structuralHash(controls));
    expect(Object.keys(L.poses).sort()).toEqual(['l', 'p', 'rs', 't']);
    expect(L.poses.t.role).toBe('rail-signal'); expect(L.poses.p.role).toBe('signal-ground'); expect(L.poses.rs.role).toBe('signal-signal'); expect(L.poses.l.role).toBe('signal-ground');
    const report = validateRailLayout(L, controls);
    expect(report.diagnostics.filter((x) => x.severity === 'error')).toEqual([]);
    expect(report.ok).toBe(true);
    expect(JSON.stringify(L)).toBe(JSON.stringify(railLayout(railInputFrom(controls, controlsGroup, ['supply', 'reference', 'load']), structuralHash(controls))));
  });
});

describe('deliberate defects fail for their NAMED reason', () => {
  const cause = (fn: () => unknown): string => { try { fn(); return 'no error'; } catch (e) { return e instanceof RailLayoutError ? e.cause_ : `other: ${e}`; } };
  it('a comparator without its − terminal → missing-port', () => {
    const c = clone(FAN_COMPOSITION); delete (c.parts[3].ports as Record<string, string>).inn;
    expect(cause(() => gen(c))).toBe('missing-port');
  });
  it('a pot without a wiper net → missing-port; a port the body does not have → unassigned-port', () => {
    const c = clone(FAN_COMPOSITION); delete (c.parts[2].ports as Record<string, string>).w; expect(cause(() => gen(c))).toBe('missing-port');
    const d = clone(FAN_COMPOSITION); (d.parts[1].ports as Record<string, string>).c = 'gate'; expect(cause(() => gen(d))).toBe('unassigned-port');
  });
  it('a wrong net against the frozen fan topology → net-mismatch; an unsupported pattern (a motor on ground) → unsupported-topology; two supplies → unsupported-topology', () => {
    const frozen = { structureSha256: structuralHash(FAN_COMPOSITION), label: 'fan.composition.json' };
    const c = clone(FAN_COMPOSITION); (c.parts[6].ports as Record<string, string>).cathode = 'motorlow'; (c.parts[6].ports as Record<string, string>).anode = 'sense';
    expect(cause(() => railLayout(railInputFrom(c, fanGroup, FAN_GROUPS), structuralHash(c), frozen))).toBe('net-mismatch');
    const m = clone(FAN_COMPOSITION); (m.parts[5].ports as Record<string, string>).plus = 'motorlow'; (m.parts[5].ports as Record<string, string>).minus = '0';
    expect(cause(() => gen(m))).toBe('unsupported-topology');
    const two = clone(FAN_COMPOSITION); two.sources.push({ ...two.sources[0], name: 'vaux', plus: 'vaux' } as Composition['sources'][number]);
    expect(cause(() => gen(two))).toBe('unsupported-topology');
    const dup = clone(FAN_COMPOSITION); (dup.parts[1] as { name: string }).name = 's'; expect(cause(() => gen(dup))).toBe('duplicate-instance');
  });
  it('a wire through a body → clearance; a body inside the rotor sweep → rotor-intrusion; a rotor below the deck → rotor-below-deck', () => {
    const L = gen(FAN_COMPOSITION);
    const hit = clone(L) as RailLayout; hit.poses.q.x = hit.wires.find((w) => w.owner === 'c' && w.kind === 'lead')!.points[0][0]; hit.poses.q.z = L.signalZ;   // the MOSFET moved onto the sense lead
    const r1 = validateRailLayout(hit, FAN_COMPOSITION); expect(r1.ok).toBe(false); expect(r1.diagnostics.some((x) => x.cause === 'clearance' && /vs q/.test(x.where))).toBe(true);
    const intr = clone(L) as RailLayout; intr.poses.fw.x = L.rotor!.x; intr.poses.fw.z = L.rotor!.z;
    const r2 = validateRailLayout(intr, FAN_COMPOSITION); expect(r2.diagnostics.some((x) => x.cause === 'rotor-intrusion' && x.where === 'fw')).toBe(true);
    const low = clone(L) as RailLayout; low.rotor!.radius = 2.0;
    const r3 = validateRailLayout(low, FAN_COMPOSITION); expect(r3.diagnostics.some((x) => x.cause === 'rotor-below-deck')).toBe(true);
  });
  it('a stale artifact (old geometry, old template, other structure) is refused before any geometry check', () => {
    const L = gen(FAN_COMPOSITION);
    const g = clone(L) as RailLayout; g.geometryVersion = 'deck-bodies-2026-09-10';   // the first table (chord-end terminals) is stale expect(validateRailLayout(g, FAN_COMPOSITION).diagnostics[0].cause).toBe('stale-geometry');
    const t = clone(L) as RailLayout; t.templateVersion = 'rail-template-0'; expect(validateRailLayout(t, FAN_COMPOSITION).diagnostics[0].cause).toBe('stale-template');
    expect(validateRailLayout(L, controls).diagnostics[0].cause).toBe('stale-structure');
    expect(TEMPLATE_VERSION).toBe('rail-template-1');
  });
  it('an unconnected crossing at deck height → ambiguous-crossing; the same crossing lifted by a tube diameter → lifted-crossing (info)', () => {
    const L = gen(FAN_COMPOSITION);
    const x = clone(L) as RailLayout; x.wires.push({ points: [[L.poses.s.x - 2, L.signalZ - 3], [L.poses.s.x + 2, L.signalZ + 3]], net: 'gate', owner: 'probe', kind: 'lead' });
    const r = validateRailLayout(x, FAN_COMPOSITION); expect(r.diagnostics.some((d) => d.cause === 'ambiguous-crossing' && /probe/.test(d.where))).toBe(true);
    const y = clone(L) as RailLayout; const pts: [number, number][] = [[L.poses.s.x - 2, L.signalZ - 3], [L.poses.s.x + 2, L.signalZ + 3]];
    y.wires.push({ points: pts, points3: pts.map((q) => [q[0], 1.6, q[1]] as [number, number, number]), net: 'gate', owner: 'probe', kind: 'cable', lift: 1.6 });   // genuinely lifted, clear of every conductor and body
    const r2 = validateRailLayout(y, FAN_COMPOSITION); expect(r2.diagnostics.some((d) => d.cause === 'ambiguous-crossing' && /probe/.test(d.where))).toBe(false); expect(r2.diagnostics.some((d) => d.cause === 'lifted-crossing' && /probe/.test(d.where))).toBe(true);
  });
  it('error → repair on LAYOUT INPUT with the circuit frozen: a builder files the flyback under a group that is not in the order; the template names it; moving it lays out and validates', () => {
    const frozen = { structureSha256: structuralHash(FAN_COMPOSITION), label: 'fan.composition.json' };
    const wrongGroup = (p: PartInstance) => p.name === 'fw' ? 'flybacks' : fanGroup(p);
    let named = ''; try { railLayout(railInputFrom(FAN_COMPOSITION, wrongGroup, FAN_GROUPS), structuralHash(FAN_COMPOSITION), frozen); } catch (e) { named = e instanceof RailLayoutError ? `${e.cause_} at ${e.where}: ${e.message}` : String(e); }
    expect(named).toMatch(/^unknown-group at fw: Part fw is in group "flybacks", which is not in the group order sensing → control → power/);
    const repaired = railLayout(railInputFrom(FAN_COMPOSITION, fanGroup, FAN_GROUPS), structuralHash(FAN_COMPOSITION), frozen);
    expect(validateRailLayout(repaired, FAN_COMPOSITION).ok).toBe(true);
    // and the tempting wrong repair — rewiring the circuit to make a layout work — is refused against the frozen topology
    const rewired = clone(FAN_COMPOSITION); (rewired.parts[6].ports as Record<string, string>).anode = 'vdd'; (rewired.parts[6].ports as Record<string, string>).cathode = 'motorlow';
    expect(cause(() => railLayout(railInputFrom(rewired, fanGroup, FAN_GROUPS), structuralHash(rewired), frozen))).toBe('net-mismatch');
  });
  it('the geometry table covers every kind the kit can emit, with two main terminals each', () => {
    for (const [kind, g] of Object.entries(BODY_GEOMETRY) as [DeckKind, typeof BODY_GEOMETRY[DeckKind]][]) { expect(g.main.length).toBe(2); for (const m of g.main) expect(g.terminals[m], `${kind}.${m}`).toBeDefined(); expect(g.halfWidth).toBeGreaterThan(0); }
  });
});

/**
 * THE GEOMETRY CORE (`checkGeometry3D`), the routine the fan page also runs on the renderer's own drawn geometry.
 * Positive control first, then each defect the rendered check found or the review asked for, by NAME.
 */
describe('the geometry core: positive control and named failures', () => {
  const nets3 = (L: RailLayout) => layoutNets(L, FAN_COMPOSITION);
  const parts3 = (L: RailLayout) => ({ wires: layoutWires3(L), bodies: layoutBodies(L), terminals: layoutTerminals(L, FAN_COMPOSITION), rotor: { hub: [L.rotor!.x, L.rotor!.hubY, L.rotor!.z] as [number, number, number], radius: L.rotor!.radius, thickness: 0.3 } });
  const errors = (r: { diagnostics: { cause: string; where: string; severity: string }[] }) => r.diagnostics.filter((x) => x.severity === 'error').map((x) => `${x.cause} ${x.where}`);
  it('positive control: the fan layout, as BOX bodies too (the renderer reports boxes), has no error; its two declared hops are the only crossings', () => {
    const L = gen(FAN_COMPOSITION); const { wires, bodies, terminals, rotor } = parts3(L);
    const r = checkGeometry3D(wires, bodies, terminals, rotor, nets3(L)); expect(errors(r)).toEqual([]);
    // the reference hop over the divider lead; the gate hop over the source drop; the comparator's lifted Vcc cable descending past its lifted ground cable
    expect(r.diagnostics.map((x) => `${x.cause} ${x.where}`).sort()).toEqual(['lifted-crossing rb:lead#2 × c:cable#11', 'lifted-crossing q:drop#13 × q:cable#14', 'lifted-crossing c:cable#9 × c:cable#10'].sort());
    const boxes = bodies.map((b) => { if (b.kind !== 'capsule') return b; const x0 = Math.min(b.a[0], b.b[0]), x1 = Math.max(b.a[0], b.b[0]), z0 = Math.min(b.a[1], b.b[1]), z1 = Math.max(b.a[1], b.b[1]); const hw = b.halfWidth; return { id: b.id, kind: 'box' as const, min: [x0 - (x1 - x0 < 1e-9 ? hw : 0), 0, z0 - (z1 - z0 < 1e-9 ? hw : 0)] as [number, number, number], max: [x1 + (x1 - x0 < 1e-9 ? hw : 0), b.height, z1 + (z1 - z0 < 1e-9 ? hw : 0)] as [number, number, number] }; });
    expect(errors(checkGeometry3D(wires, boxes, terminals, rotor, nets3(L), { endEps: 0.15 }))).toEqual([]);
  });
  it('a drop hugging a horizontal package (the MOSFET source drop, as first drawn) → clearance, measured against the package face', () => {
    const L = gen(FAN_COMPOSITION); const q = L.wires.find((w) => w.owner === 'q' && w.kind === 'drop')!; const end = q.points[0], row = q.points[q.points.length - 1];
    q.points = [end, [end[0], row[1]]];   // straight off the terminal, alongside the package
    const r = validateRailLayout(L, FAN_COMPOSITION); const hit = r.diagnostics.find((x) => x.cause === 'clearance' && /^q:drop/.test(x.where) && / vs q$/.test(x.where));
    expect(hit).toBeDefined(); expect(hit!.measured!).toBeLessThan(0.15);
  });
  it('a gate cable at deck height over its own body\'s source drop → ambiguous-crossing (one body\'s pins are exempt only OVER that body); lifted → lifted-crossing info', () => {
    const L = gen(FAN_COMPOSITION); const g = L.wires.find((w) => w.owner === 'q' && w.kind === 'cable')!; const a = g.points3![0], b = g.points3![g.points3!.length - 1];
    const flat = cablePoints3(a, b, .45, 0); g.points3 = flat; g.points = flat.map((p) => [p[0], p[2]]); delete g.lift;
    const r = validateRailLayout(L, FAN_COMPOSITION); expect(r.diagnostics.some((x) => x.cause === 'ambiguous-crossing' && x.where === 'q:drop#13 × q:cable#14')).toBe(true);
    const M = gen(FAN_COMPOSITION); const r2 = validateRailLayout(M, FAN_COMPOSITION); expect(r2.ok).toBe(true); expect(r2.diagnostics.some((x) => x.cause === 'lifted-crossing' && x.where === 'q:drop#13 × q:cable#14')).toBe(true);
    // the comparator's lifted vcc and gnd cables meet over its own plate only as a height-separated crossing, reported not hidden
    expect(r2.diagnostics.some((x) => x.cause === 'ambiguous-crossing' && /c:cable#9 × c:cable#10/.test(x.where))).toBe(false);
    expect(r2.diagnostics.some((x) => x.cause === 'lifted-crossing' && /c:cable#9 × c:cable#10/.test(x.where))).toBe(true);
  });
  it('a lead drawn straight to the net\'s feed instead of its drop (the divider\'s ground lead, as the renderer first drew it) → ambiguous-crossing with the pot\'s drop', () => {
    const L = gen(FAN_COMPOSITION); const rb = L.wires.find((w) => w.owner === 'rb' && w.kind === 'drop')!; rb.points = [rb.points[0], [ROWS.feedX, L.ground.z]];
    const r = validateRailLayout(L, FAN_COMPOSITION); expect(r.diagnostics.some((x) => x.cause === 'ambiguous-crossing' && x.where === 'rb:drop#3 × p:drop#5')).toBe(true);
  });
  it('one missing drop → coverage on its terminal; a missing bus → disconnected-net; a wire end within endEps still lands (the renderer lifts conductors 0.06)', () => {
    const L = gen(FAN_COMPOSITION); const { wires, bodies, terminals, rotor } = parts3(L);
    const without = wires.filter((w) => w.id !== 'q:drop#13'); const r = checkGeometry3D(without, bodies, terminals, rotor, nets3(L));
    expect(errors(r)).toContain('coverage q.source');
    const noBus = wires.filter((w) => w.id !== 'ground:bus#20'); expect(errors(checkGeometry3D(noBus, bodies, terminals, rotor, nets3(L)))).toContain('disconnected-net 0');
    const lifted = wires.map((w) => ({ ...w, points: w.points.map((p) => [p[0], p[1] + 0.06, p[2]] as [number, number, number]) }));
    expect(errors(checkGeometry3D(lifted, bodies, terminals, rotor, nets3(L), { endEps: 0.15 }))).toEqual([]);
    expect(errors(checkGeometry3D(lifted, bodies, terminals, rotor, nets3(L), { endEps: 0.03 })).length).toBeGreaterThan(0);   // and with a tighter tolerance the same lift is a miss
  });
  it('exact distances: a long wire tunnelling through a narrow box between any sample spacing → clearance; a cable leaving a pin through its own package → clearance; the same cable leaving along the pin\'s exit → passes', () => {
    const box = { id: 'chip', kind: 'box' as const, min: [0.8, -0.2, -0.2] as [number, number, number], max: [1.2, 0.2, 0.2] as [number, number, number] };
    expect(errors(checkGeometry3D([{ id: 'long', net: 'n', owner: 'w', kind: 'lead', points: [[0, 0, 0], [1000, 0, 0]] }], [box], [], null, {}))).toContain('clearance long[0] vs chip');
    const chip = { id: 'chip', kind: 'box' as const, min: [-1, -1, -1] as [number, number, number], max: [1, 1, 1] as [number, number, number] };
    const pin = { part: 'chip', port: 'pin', net: 'n', at: [-1, 0, 0] as [number, number, number], out: [-1, 0, 0] as [number, number, number] };
    expect(errors(checkGeometry3D([{ id: 'through', net: 'n', owner: 'chip', kind: 'cable', points: [[-1, 0, 0], [3, 0, 0]] }], [chip], [pin], null, { n: ['chip.pin'] }))).toContain('clearance through[0] vs chip');
    expect(errors(checkGeometry3D([{ id: 'away', net: 'n', owner: 'chip', kind: 'cable', points: [[-1, 0, 0], [-4, 0, 0]] }], [chip], [pin], null, { n: ['chip.pin'] }))).toEqual([]);
    // the joint at the pin: a cable arriving diagonally onto the pin is not a clearance failure, one running along the face beyond the joint is
    expect(errors(checkGeometry3D([{ id: 'diag', net: 'n', owner: 'chip', kind: 'cable', points: [[-4, 3, 0], [-1, 0, 0]] }], [chip], [pin], null, { n: ['chip.pin'] }))).toEqual([]);
    expect(errors(checkGeometry3D([{ id: 'along', net: 'n', owner: 'chip', kind: 'cable', points: [[-1, 0, 0], [-1, 0, 3]] }], [chip], [pin], null, { n: ['chip.pin'] }))).toContain('clearance along[0] vs chip');
  });
  it('same-net conductors: close within a junction\'s fan-out radius pass; the same pair running close away from any junction → ambiguous-crossing', () => {
    const fanOut: Wire3[] = [{ id: 'a', net: 'n', owner: 'x', kind: 'lead', points: [[0, 0, 0], [1, 0, 0]] }, { id: 'b', net: 'n', owner: 'y', kind: 'lead', points: [[1, 0, 0], [1.9, 0.3, 0]] }];
    expect(errors(checkGeometry3D(fanOut, [], [], null, {}))).toEqual([]);
    const parallel: Wire3[] = [{ id: 'a', net: 'n', owner: 'x', kind: 'lead', points: [[0, 0, 0], [4, 0, 0]] }, { id: 'b', net: 'n', owner: 'y', kind: 'lead', points: [[4, 0, 0], [4, 0, 0.3], [0, 0, 0.3]] }];
    expect(errors(checkGeometry3D(parallel, [], [], null, {}))).toContain('ambiguous-crossing a × b');
  });
});

describe('capacitor and inductor in the template (core-primitives first batch)', () => {
  const fixture = (name: string) => JSON.parse(readFileSync(new URL(`../../tools/conformance/fixtures/${name}.composition.json`, import.meta.url), 'utf8')) as Composition;
  // One group: the template stacks each storing part under the part that feeds it. (Two groups — resistors then
  // capacitors — put the ladder's second resistor over the first capacitor's column: the validator refused that
  // layout by name, clearance + ambiguous-crossing, as it should; the group order is authoring input.)
  const oneGroup = (_p: PartInstance): string => 'all';
  for (const name of ['rc-step', 'rl-step', 'rc-ladder']) {
    it(`${name}: lays out from its composition and validates`, () => {
      const c = fixture(name); const L = railLayout(railInputFrom(c, oneGroup, ['all']), structuralHash(c));
      const r = validateRailLayout(L, c); expect(r.diagnostics.filter((d) => d.severity === 'error')).toEqual([]); expect(r.ok).toBe(true);
      expect(Object.keys(L.poses).length).toBe(c.parts.length);
      expect(JSON.stringify(railLayout(railInputFrom(c, oneGroup, ['all']), structuralHash(c)))).toBe(JSON.stringify(L));
    });
  }
  it('an inductor from rail to ground is not a pattern the table has → unsupported-topology, by name', () => {
    const c = fixture('rl-step'); (c.parts[1].ports as { plus: string; minus: string }) = { plus: 'vin', minus: '0' };
    const cause = (fn: () => unknown): string => { try { fn(); return 'no error'; } catch (e) { return e instanceof RailLayoutError ? e.cause_ : `other: ${e}`; } };
    expect(cause(() => railLayout(railInputFrom(c, oneGroup, ['all']), structuralHash(c)))).toBe('unsupported-topology');
  });
});
